apiVersion: plugin.halo.run/v1alpha1
kind: ReverseProxy
metadata:
  name: reverse-proxy-template
  labels:
    plugin.halo.run/plugin-name: PluginLinks
rules:
  - path: /static/**
    file:
      directory: static